/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ADMIN
 */
public class BieuDoThongKeForm extends javax.swing.JFrame {
    
    /**
     * Creates new form BieuDoThongKeForm với 2 dataset
     */
    public BieuDoThongKeForm(DefaultCategoryDataset datasetVe, DefaultCategoryDataset datasetDoanhThu) {
        initComponents();
        hienThiBieuDo(datasetVe, datasetDoanhThu);
        this.pack();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form BieuDoThongKeForm với 1 dataset
     */
    public BieuDoThongKeForm(DefaultCategoryDataset dataset) {
        initComponents();
        hienThiBieuDoDon(dataset);
        this.pack();
        this.setLocationRelativeTo(null);
    }
    
    private void hienThiBieuDo(DefaultCategoryDataset datasetVe, DefaultCategoryDataset datasetDoanhThu) {
        // Tạo JTabbedPane để hiển thị 2 tab
        JTabbedPane tabbedPane = new JTabbedPane();
        
        // Tab 1: Biểu đồ số vé
        JFreeChart chartVe = ChartFactory.createBarChart(
            "BIỂU ĐỒ SỐ VÉ BÁN THEO PHIM",
            "Tên Phim",
            "Số Vé Bán",
            datasetVe
        );
        chartVe.getTitle().setFont(new Font("Arial", Font.BOLD, 16));
        chartVe.setBackgroundPaint(Color.WHITE);
        
        ChartPanel panelVe = new ChartPanel(chartVe);
        panelVe.setPreferredSize(new Dimension(800, 500));
        tabbedPane.addTab("Số Vé Bán", panelVe);
        
        // Tab 2: Biểu đồ doanh thu
        JFreeChart chartDoanhThu = ChartFactory.createBarChart(
            "BIỂU ĐỒ DOANH THU THEO PHIM",
            "Tên Phim",
            "Doanh Thu (VND)",
            datasetDoanhThu
        );
        chartDoanhThu.getTitle().setFont(new Font("Arial", Font.BOLD, 16));
        chartDoanhThu.setBackgroundPaint(Color.WHITE);
        
        ChartPanel panelDoanhThu = new ChartPanel(chartDoanhThu);
        panelDoanhThu.setPreferredSize(new Dimension(800, 500));
        tabbedPane.addTab("Doanh Thu", panelDoanhThu);
        
        // Đặt tabbedPane làm content pane
        setContentPane(tabbedPane);
    }
    
    private void hienThiBieuDoDon(DefaultCategoryDataset dataset) {
        // Tạo biểu đồ đơn giản
        JFreeChart chart = ChartFactory.createBarChart(
            "BIỂU ĐỒ THỐNG KÊ SỐ VÉ BÁN THEO PHIM",
            "Tên Phim",
            "Số Vé Bán",
            dataset
        );
        
        chart.getTitle().setFont(new Font("Arial", Font.BOLD, 16));
        chart.setBackgroundPaint(Color.WHITE);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(800, 600));
        setContentPane(chartPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Biểu Đồ Thống Kê");
        setPreferredSize(new java.awt.Dimension(850, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BieuDoThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BieuDoThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BieuDoThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BieuDoThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Tạo dataset mẫu để test
                DefaultCategoryDataset datasetVe = new DefaultCategoryDataset();
                datasetVe.addValue(120, "Số vé", "Avengers");
                datasetVe.addValue(85, "Số vé", "Spider-Man");
                datasetVe.addValue(150, "Số vé", "Batman");
                
                DefaultCategoryDataset datasetDoanhThu = new DefaultCategoryDataset();
                datasetDoanhThu.addValue(12000000, "Doanh thu", "Avengers");
                datasetDoanhThu.addValue(8500000, "Doanh thu", "Spider-Man");
                datasetDoanhThu.addValue(15000000, "Doanh thu", "Batman");
                
                new BieuDoThongKeForm(datasetVe, datasetDoanhThu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}